# Le bureau SPI EtR est lancé par un service système et non par une session
# graphique logind. La surveillance de siège empêcherait donc WirePlumber
# d'enregistrer les profils audio Bluetooth pour l'utilisateur oryx.
wireplumber.profiles = {
  main = {
    monitor.bluez.seat-monitoring = disabled
  }
}

monitor.bluez.properties = {
  bluez5.roles = [ a2dp_source a2dp_sink hfp_hf hfp_ag ]
  bluez5.codecs = [ sbc sbc_xq ]
  bluez5.enable-sbc-xq = true
}

monitor.bluez.rules = [
  {
    matches = [
      { device.name = "~bluez_card.*" }
    ]
    actions = {
      update-props = {
        bluez5.auto-connect = [ a2dp_source ]
        bluez5.hw-volume = [ a2dp_source ]
        device.profile = "a2dp-sink"
      }
    }
  }
]
